# Generated by Django 4.2.4 on 2023-09-01 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value1', models.CharField(choices=[('UZS', "O'zbekiston So'mi"), ('USD', 'Amerika Dollari'), ('RUB', 'Rossiya Rubli'), ('KZT', 'Qozoqiston Tengesi'), ('TRY', 'Turikya Lirasi'), ('EUR', 'Yevro')], default='USD', max_length=10)),
                ('value2', models.CharField(choices=[('UZS', "O'zbekiston So'mi"), ('USD', 'Amerika Dollari'), ('RUB', 'Rossiya Rubli'), ('KZT', 'Qozoqiston Tengesi'), ('TRY', 'Turikya Lirasi'), ('EUR', 'Yevro')], default='UZS', max_length=10)),
                ('value', models.BigIntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 9, 2, 2, 27, 24, 889286))),
            ],
        ),
    ]
